{% set version = "0.6.3" %}

package:
  name: jupyter_nbextensions_configurator
  version: {{ version }}

source:
  url: https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator/archive/refs/tags/{{ version }}.tar.gz
  sha256: 6ec41b4be8ba8df25fdc23f224976b6e46ecb00405317cb197b94d973305c9d1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - jupyter-nbextensions_configurator = jupyter_nbextensions_configurator.application:main


requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - jupyter_contrib_core >=0.3.3
    - jupyter_core
    - notebook >=6.0
    - pyyaml
    - tornado
    - traitlets

test:
  imports:
    - jupyter_nbextensions_configurator
    - jupyter_nbextensions_configurator.application
  requires:
    - pip
  commands:
    - jupyter nbextensions_configurator --help
    - jupyter nbextensions_configurator enable --help
    - jupyter nbextensions_configurator disable --help
    - pip check

about:
  summary: A server extension for jupyter notebook providing configuration interfaces for notebook extensions (nbextensions).
  home: https://github.com/jupyter-contrib/jupyter_nbextensions_configurator
  license_file: LICENSE.txt
  license: BSD-3-Clause

extra:
  recipe-maintainers:
    - jcb91
    - xhochy
