schema_version: 1

context:
  version: "0.6.1"

package:
  name: jupyter_nbextensions_configurator
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyter_nbextensions_configurator/jupyter_nbextensions_configurator-${{ version }}.tar.gz
  sha256: 4b9e1270ccc1f8e0a421efb8979a737f586813023a4855b9453f61c3ca599b82

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - jupyter-nbextensions_configurator = jupyter_nbextensions_configurator.application:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
  run:
    - python >=${{ python_min }}
    - jupyter_contrib_core >=0.3.3
    - jupyter_core
    - notebook >=6.0
    - pyyaml
    - tornado
    - traitlets

tests:
  - python:
      imports:
        - jupyter_nbextensions_configurator
        - jupyter_nbextensions_configurator.application
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - script:
      - jupyter nbextensions_configurator --help
      - jupyter nbextensions_configurator enable --help
      - jupyter nbextensions_configurator disable --help

about:
  summary: A server extension for jupyter notebook providing configuration interfaces for notebook extensions (nbextensions).
  license_file: LICENSE.txt
  license: BSD-3-Clause
  homepage: https://github.com/jupyter-contrib/jupyter_nbextensions_configurator

extra:
  recipe-maintainers:
    - jcb91
    - xhochy
